#!/usr/bin/env node
// export-scenes.mjs — the approved reel's product scenes, packaged for the
// agents. Reads clipkit/meridian-sizzle.json (the composition Otis approved on
// Sep 6) and writes two files next to it:
//   video-scenes.json — the seven product scene groups with their time
//     windows, plus the fonts and styles they rely on;
//   video-scenes.sql  — the same, as an upsert of settings key "video_scenes".
// _shared/clipkit.ts loads that settings row at run time and assembles every
// agent video from these scenes, so what the agents render IS the approved
// work, re-sequenced around fresh words. Nothing is bundled into the edge
// functions: a newly approved reel is one SQL statement, no redeploy.
// Re-run after editing the sizzle; apply the SQL (Supabase MCP execute_sql,
// or the SQL editor); commit both outputs.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const src = JSON.parse(fs.readFileSync(path.join(here, "meridian-sizzle.json"), "utf8"));
const out = path.join(here, "video-scenes.json");
const sql = path.join(here, "video-scenes.sql");

// What each scene shows, for the model choosing between them.
const SCENES = {
  g1: { id: "website", label: "Website", description: "a wireframe assembling line by line, then snapping into the finished Meridian site: hero, three service cards, call to action" },
  g2: { id: "app", label: "Mobile app", description: "a phone with a banking-style app: activity, card, transactions - 'Mobile apps your customers keep'" },
  g3: { id: "storefront", label: "Storefront", description: "the Modern Street online store: six real product photos, add-to-bag click, toast" },
  g4: { id: "dashboard", label: "Dashboard", description: "a performance dashboard: KPI tiles counting up, bars and a chart animating" },
  g5: { id: "crm", label: "CRM", description: "the CRM: pipeline columns, lead cards sliding in, in the CRM's own mint and emerald" },
  g6: { id: "stack", label: "AI tech stack", description: "five stacked layers of an AI stack: foundation models, agent framework, memory, tools, governance - 'Five layers, planned before it's built'" },
  g7: { id: "code", label: "Code to UI", description: "React code typing in, resolving into the live website's hero and button" },
};

function windowOf(group) {
  const op = (group.keyframe_animations ?? []).find((k) => k.property === "opacity");
  const kf = op?.keyframes ?? [];
  let start = null, end = null;
  for (let i = 1; i < kf.length; i++) {
    if (kf[i].value === 1 && kf[i - 1].value === 0 && start === null) start = kf[i - 1].time;
    if (kf[i].value === 0 && kf[i - 1].value === 1) end = kf[i].time;
  }
  return { start, end };
}

// Photographs are re-pointed at our own bucket. Clipkit's cloud renderer
// cannot fetch meridianinterface.com (the storefront tiles rendered blank,
// Sep 7), but it fetches the social-videos bucket fine - that is where the
// soundtrack already lives. The copies are put there by the `media` edge
// function (action ingest, slug modern-street-<file>); see SESSION.md Sep 7.
const PHOTO_SRC = "https://meridianinterface.com/demos/modern-street/images/products/";
const PHOTO_DST = "https://glzodwhyavexpuusbqjy.supabase.co/storage/v1/object/public/social-videos/library/modern-street-";
function rehost(node) {
  if (Array.isArray(node)) return node.map(rehost);
  if (!node || typeof node !== "object") return node;
  const out = {};
  for (const [k, v] of Object.entries(node)) {
    out[k] = (k === "source" && typeof v === "string" && v.startsWith(PHOTO_SRC))
      ? PHOTO_DST + v.slice(PHOTO_SRC.length).replace(/\.jpe?g$/i, ".jpg")
      : rehost(v);
  }
  return out;
}

const scenes = [];
for (const el of src.elements) {
  if (el.type !== "group" || !SCENES[el.id]) continue;
  const { start, end } = windowOf(el);
  const centered = el.x_anchor === "50%";
  scenes.push({ ...SCENES[el.id], source_id: el.id, start, end, length: Number((end - start).toFixed(2)), centered, group: rehost(el) });
}
scenes.sort((a, b) => a.start - b.start);

const doc = {
  generated_from: "system/motion/clipkit/meridian-sizzle.json",
  width: src.width, height: src.height,
  fonts: src.fonts, styles: src.styles,
  scenes,
};
fs.writeFileSync(out, JSON.stringify(doc));
// Dollar-quoted so the scene text ("it's built.") needs no escaping.
fs.writeFileSync(sql,
  `-- generated by export-scenes.mjs from meridian-sizzle.json; do not edit by hand\n` +
  `insert into public.settings (key, value) values ('video_scenes', $scenes$${JSON.stringify(doc)}$scenes$::jsonb)\n` +
  `on conflict (key) do update set value = excluded.value, updated_at = now();\n`);
console.log(`wrote ${path.relative(process.cwd(), out)} and .sql: ${scenes.map((s) => `${s.id} ${s.start}-${s.end}`).join(", ")}`);
