// Sample homes for previewing the hologram in other styles and layouts.
// Every sample keeps Haven's device rooms (kitchen, living, primary, hallway,
// garage, utility) so the live lights, alerts and controls still work, and
// adds the rooms its style of home would have. Screens → Home style.
//
// A real home describes itself in config/home.json (see docs/HOME-PLAN.md);
// these are only previews.

export const SAMPLE_HOMES = [
  {
    id: "colonial",
    label: "Two-story Colonial",
    about: "Center hall, formal rooms down, four bedrooms up, side garage.",
    building: {
      style: "colonial",
      floors: [{ id: "ground", name: "Ground floor" }, { id: "upper", name: "Upstairs" }],
      features: [{ type: "porch", plan: [11, 9, 5, 1.6] }, { type: "driveway", plan: [0, 7, 6, 5] }],
    },
    rooms: [
      { id: "garage", name: "Garage", plan: [0, 0, 6, 7] },
      { id: "living", name: "Living Room", plan: [6, 0, 6, 5] },
      { id: "utility", name: "Utility Room", plan: [6, 5, 3, 4] },
      { id: "bath", name: "Powder Room", plan: [9, 5, 3, 4] },
      { id: "hallway", name: "Hallway", plan: [12, 0, 3, 9] },
      { id: "dining", name: "Dining Room", plan: [15, 0, 5, 5] },
      { id: "kitchen", name: "Kitchen", plan: [15, 5, 5, 4] },
      { id: "primary", name: "Primary Bedroom", floor: "upper", plan: [6, 0, 6, 5] },
      { id: "bath2", name: "Primary Bath", floor: "upper", plan: [6, 5, 3, 4] },
      { id: "closet", name: "Walk-in Closet", floor: "upper", plan: [9, 5, 3, 4] },
      { id: "landing", name: "Landing", floor: "upper", plan: [12, 0, 3, 9] },
      { id: "bed2", name: "Bedroom 2", floor: "upper", plan: [15, 0, 5, 5] },
      { id: "bed3", name: "Bedroom 3", floor: "upper", plan: [15, 5, 5, 4] },
    ],
  },
  {
    id: "farmhouse",
    label: "Farmhouse",
    about: "One story, big open living room, wraparound porch.",
    building: { style: "farmhouse", features: [{ type: "driveway", plan: [0, -5, 6, 5] }] },
    rooms: [
      { id: "garage", name: "Garage", plan: [0, 0, 6, 6] },
      { id: "utility", name: "Mudroom", plan: [0, 6, 6, 3] },
      { id: "kitchen", name: "Kitchen", plan: [6, 0, 6, 5] },
      { id: "dining", name: "Dining Room", plan: [12, 0, 5, 5] },
      { id: "living", name: "Living Room", plan: [6, 5, 11, 5] },
      { id: "hallway", name: "Hallway", plan: [17, 0, 3, 10] },
      { id: "primary", name: "Primary Bedroom", plan: [20, 0, 6, 6] },
      { id: "bath", name: "Bath", plan: [20, 6, 3, 4] },
      { id: "bed2", name: "Bedroom 2", plan: [23, 6, 3, 4] },
    ],
  },
  {
    id: "craftsman",
    label: "Craftsman Bungalow",
    about: "An L-shaped living room, deep front porch, wide eaves.",
    building: { style: "craftsman", features: [{ type: "driveway", plan: [17, -5, 6, 5] }] },
    rooms: [
      { id: "living", name: "Living Room", shape: [[4, 0], [12, 0], [12, 4], [8, 4], [8, 7], [4, 7]] },
      { id: "kitchen", name: "Kitchen", plan: [12, 0, 5, 5] },
      { id: "dining", name: "Dining Nook", plan: [8, 4, 4, 3] },
      { id: "hallway", name: "Hallway", plan: [12, 5, 5, 2] },
      { id: "primary", name: "Primary Bedroom", plan: [12, 7, 5, 5] },
      { id: "bath", name: "Bath", plan: [8, 7, 4, 2.5] },
      { id: "utility", name: "Laundry", plan: [8, 9.5, 4, 2.5] },
      { id: "bed2", name: "Bedroom 2", plan: [4, 7, 4, 5] },
      { id: "garage", name: "Garage", plan: [17, 0, 6, 6] },
    ],
  },
  {
    id: "ranch",
    label: "Ranch",
    about: "Long and low under a hip roof, everything on one level.",
    building: { style: "ranch", features: [{ type: "patio", plan: [9, 10, 10, 3] }] },
    rooms: [
      { id: "garage", name: "Garage", plan: [0, 0, 6, 6] },
      { id: "utility", name: "Laundry", plan: [6, 0, 3, 6] },
      { id: "kitchen", name: "Kitchen", plan: [9, 0, 6, 5] },
      { id: "dining", name: "Dining Room", plan: [15, 0, 4, 5] },
      { id: "living", name: "Family Room", plan: [9, 5, 10, 5] },
      { id: "hallway", name: "Hallway", plan: [19, 0, 2, 10] },
      { id: "primary", name: "Primary Bedroom", plan: [21, 0, 6, 5] },
      { id: "bath", name: "Bath", plan: [21, 5, 3, 5] },
      { id: "bed2", name: "Bedroom 2", plan: [24, 5, 3, 5] },
      { id: "office", name: "Office", plan: [27, 0, 4, 5] },
    ],
  },
  {
    id: "contemporary",
    label: "Contemporary",
    about: "Two stories under a shed roof, a deck off the living room and a pool.",
    building: {
      style: "contemporary",
      floors: [{ id: "ground", name: "Ground floor" }, { id: "upper", name: "Upstairs" }],
      features: [{ type: "deck", plan: [16, 1, 4, 9] }, { type: "pool", plan: [8, 12, 8, 3] }, { type: "patio", plan: [6, 11, 12, 5] }],
    },
    rooms: [
      { id: "garage", name: "Garage", plan: [0, 0, 6, 6] },
      { id: "utility", name: "Utility Room", plan: [0, 6, 3, 3] },
      { id: "hallway", name: "Entry", plan: [3, 6, 3, 3] },
      { id: "kitchen", name: "Kitchen", plan: [6, 0, 6, 5] },
      { id: "dining", name: "Dining", plan: [12, 0, 4, 5] },
      { id: "living", name: "Living Room", plan: [6, 5, 10, 6] },
      { id: "primary", name: "Primary Suite", floor: "upper", plan: [6, 0, 6, 6] },
      { id: "office", name: "Office", floor: "upper", plan: [12, 0, 4, 6] },
      { id: "bath2", name: "Bath", floor: "upper", plan: [6, 6, 4, 3] },
      { id: "landing", name: "Landing", floor: "upper", plan: [10, 6, 6, 3] },
    ],
  },
  {
    id: "mediterranean",
    label: "Mediterranean",
    about: "Rooms around a courtyard, arched windows, low tile roof.",
    building: { style: "mediterranean", features: [{ type: "patio", plan: [6, 7, 7, 6] }, { type: "pool", plan: [7.5, 9, 4, 2.5] }] },
    rooms: [
      { id: "garage", name: "Garage", plan: [0, 0, 6, 6] },
      { id: "utility", name: "Utility Room", plan: [0, 6, 6, 3] },
      { id: "bed2", name: "Guest Room", plan: [0, 9, 6, 4] },
      { id: "kitchen", name: "Kitchen", plan: [6, 0, 6, 5] },
      { id: "dining", name: "Dining Room", plan: [12, 0, 5, 5] },
      { id: "hallway", name: "Gallery", plan: [6, 5, 11, 2] },
      { id: "living", name: "Living Room", plan: [17, 0, 7, 7] },
      { id: "bath", name: "Bath", plan: [13, 7, 4, 4] },
      { id: "primary", name: "Primary Bedroom", plan: [17, 7, 7, 6] },
    ],
  },
  {
    id: "cabin",
    label: "Cabin",
    about: "Compact, steep roof and chimney, porch across the front.",
    building: { style: "cabin" },
    rooms: [
      { id: "living", name: "Great Room", plan: [0, 0, 7, 6] },
      { id: "kitchen", name: "Kitchen", plan: [7, 0, 5, 4] },
      { id: "bath", name: "Bath", plan: [7, 4, 2.5, 2] },
      { id: "utility", name: "Utility", plan: [9.5, 4, 2.5, 2] },
      { id: "hallway", name: "Hall", plan: [0, 6, 4, 2] },
      { id: "primary", name: "Bedroom", plan: [4, 6, 8, 4] },
      { id: "garage", name: "Garage", plan: [12, 0, 6, 6] },
    ],
  },
  {
    id: "rooms-only",
    label: "From a room list",
    about: "No floor plan, only room names: Haven lays it out for you.",
    building: { style: "ranch" },
    rooms: [
      { id: "garage", name: "Garage" }, { id: "utility", name: "Laundry" }, { id: "kitchen", name: "Kitchen" },
      { id: "living", name: "Living Room" }, { id: "dining", name: "Dining Room" }, { id: "hallway", name: "Hallway" },
      { id: "primary", name: "Primary Bedroom" }, { id: "bed2", name: "Bedroom 2" }, { id: "bath", name: "Bath" }, { id: "office", name: "Office" },
    ],
  },
];
